<?xml version="1.0" encoding="utf-8"?><!DOCTYPE context [<!ELEMENT context (device | context-attribute)*><!ELEMENT context-attribute EMPTY><!ELEMENT device (channel | buffer | attribute | debug-attribute | buffer-attribute)*><!ELEMENT channel (scan-element?, attribute*)><!ELEMENT buffer (attribute)*><!ELEMENT attribute EMPTY><!ELEMENT scan-element EMPTY><!ELEMENT debug-attribute EMPTY><!ELEMENT buffer-attribute EMPTY><!ATTLIST context name CDATA #REQUIRED version-major CDATA #REQUIRED version-minor CDATA #REQUIRED version-git CDATA #REQUIRED description CDATA #IMPLIED><!ATTLIST context-attribute name CDATA #REQUIRED value CDATA #REQUIRED><!ATTLIST device id CDATA #REQUIRED name CDATA #IMPLIED label CDATA #IMPLIED><!ATTLIST channel id CDATA #REQUIRED type (input|output) #REQUIRED name CDATA #IMPLIED label CDATA #IMPLIED><!ATTLIST buffer index CDATA #REQUIRED><!ATTLIST scan-element index CDATA #REQUIRED format CDATA #REQUIRED scale CDATA #IMPLIED><!ATTLIST attribute name CDATA #REQUIRED filename CDATA #IMPLIED value CDATA #IMPLIED><!ATTLIST debug-attribute name CDATA #REQUIRED value CDATA #IMPLIED><!ATTLIST buffer-attribute name CDATA #REQUIRED value CDATA #IMPLIED>]><context name="ip" version-major="0" version-minor="26" version-git="v0.26" description="Linux (none) 6.1.0-gf3da30df6004 #5 SMP PREEMPT Tue Oct 15 10:50:00 CEST 2024 armv7l 192.168.2.1" ><context-attribute name="ad9361-phy,model" value="ad9363a" /><context-attribute name="ad9361-phy,xo_correction" value="40000000" /><context-attribute name="fw_version" value="v0.39" /><context-attribute name="hw_model" value="Analog Devices PlutoSDR Rev.B (Z7010-AD9363A)" /><context-attribute name="hw_model_variant" value="1" /><context-attribute name="hw_serial" value="104473ce6991000604002900e7b6894c46" /><context-attribute name="ip,ip-addr" value="192.168.2.1" /><context-attribute name="local,kernel" value="6.1.0-gf3da30df6004" /><context-attribute name="uri" value="ip:192.168.2.1" /><device id="iio:device0" name="adm1177-iio" ><channel id="voltage0" type="input" ><attribute name="raw" filename="in_voltage0_raw" value="730" /><attribute name="scale" filename="in_voltage0_scale" value="6.433105468" /></channel><channel id="current0" type="input" ><attribute name="raw" filename="in_current0_raw" value="813" /><attribute name="scale" filename="in_current0_scale" value="0.516601562" /></channel><attribute name="waiting_for_supplier" value="0" /></device><device id="iio:device1" name="ad9361-phy" ><channel id="altvoltage1" name="TX_LO" type="output" ><attribute name="external" filename="out_altvoltage1_TX_LO_external" value="0" /><attribute name="fastlock_load" filename="out_altvoltage1_TX_LO_fastlock_load" value="0" /><attribute name="fastlock_recall" filename="out_altvoltage1_TX_LO_fastlock_recall" value="ERROR:-22" /><attribute name="fastlock_save" filename="out_altvoltage1_TX_LO_fastlock_save" value="0 66,66,66,66,66,66,66,66,66,66,66,66,66,66,66,66" /><attribute name="fastlock_store" filename="out_altvoltage1_TX_LO_fastlock_store" value="0" /><attribute name="frequency" filename="out_altvoltage1_TX_LO_frequency" value="2450000000" /><attribute name="frequency_available" filename="out_altvoltage1_TX_LO_frequency_available" value="[325000000 1 3800000000]" /><attribute name="label" filename="out_altvoltage1_TX_LO_label" value="TX_LO" /><attribute name="powerdown" filename="out_altvoltage1_TX_LO_powerdown" value="0" /></channel><channel id="voltage0" type="input" ><attribute name="bb_dc_offset_tracking_en" filename="in_voltage_bb_dc_offset_tracking_en" value="1" /><attribute name="filter_fir_en" filename="in_voltage_filter_fir_en" value="0" /><attribute name="gain_control_mode" filename="in_voltage0_gain_control_mode" value="slow_attack" /><attribute name="gain_control_mode_available" filename="in_voltage_gain_control_mode_available" value="manual fast_attack slow_attack hybrid" /><attribute name="hardwaregain" filename="in_voltage0_hardwaregain" value="71.000000 dB" /><attribute name="hardwaregain_available" filename="in_voltage0_hardwaregain_available" value="[-3 1 71]" /><attribute name="quadrature_tracking_en" filename="in_voltage_quadrature_tracking_en" value="1" /><attribute name="rf_bandwidth" filename="in_voltage_rf_bandwidth" value="18000000" /><attribute name="rf_bandwidth_available" filename="in_voltage_rf_bandwidth_available" value="[200000 1 56000000]" /><attribute name="rf_dc_offset_tracking_en" filename="in_voltage_rf_dc_offset_tracking_en" value="1" /><attribute name="rf_port_select" filename="in_voltage0_rf_port_select" value="A_BALANCED" /><attribute name="rf_port_select_available" filename="in_voltage_rf_port_select_available" value="A_BALANCED B_BALANCED C_BALANCED A_N A_P B_N B_P C_N C_P TX_MONITOR1 TX_MONITOR2 TX_MONITOR1_2" /><attribute name="rssi" filename="in_voltage0_rssi" value="102.50 dB" /><attribute name="sampling_frequency" filename="in_voltage_sampling_frequency" value="30720000" /><attribute name="sampling_frequency_available" filename="in_voltage_sampling_frequency_available" value="[2083333 1 61440000]" /></channel><channel id="voltage3" type="output" ><attribute name="filter_fir_en" filename="out_voltage_filter_fir_en" value="0" /><attribute name="raw" filename="out_voltage3_raw" value="306" /><attribute name="rf_bandwidth" filename="out_voltage_rf_bandwidth" value="18000000" /><attribute name="rf_bandwidth_available" filename="out_voltage_rf_bandwidth_available" value="[200000 1 40000000]" /><attribute name="rf_port_select_available" filename="out_voltage_rf_port_select_available" value="A B" /><attribute name="sampling_frequency" filename="out_voltage_sampling_frequency" value="30720000" /><attribute name="sampling_frequency_available" filename="out_voltage_sampling_frequency_available" value="[2083333 1 61440000]" /><attribute name="scale" filename="out_voltage3_scale" value="1.000000" /></channel><channel id="altvoltage0" name="RX_LO" type="output" ><attribute name="external" filename="out_altvoltage0_RX_LO_external" value="0" /><attribute name="fastlock_load" filename="out_altvoltage0_RX_LO_fastlock_load" value="0" /><attribute name="fastlock_recall" filename="out_altvoltage0_RX_LO_fastlock_recall" value="ERROR:-22" /><attribute name="fastlock_save" filename="out_altvoltage0_RX_LO_fastlock_save" value="0 93,93,93,93,93,93,93,93,93,93,93,93,93,93,93,93" /><attribute name="fastlock_store" filename="out_altvoltage0_RX_LO_fastlock_store" value="0" /><attribute name="frequency" filename="out_altvoltage0_RX_LO_frequency" value="2400000000" /><attribute name="frequency_available" filename="out_altvoltage0_RX_LO_frequency_available" value="[325000000 1 3800000000]" /><attribute name="label" filename="out_altvoltage0_RX_LO_label" value="RX_LO" /><attribute name="powerdown" filename="out_altvoltage0_RX_LO_powerdown" value="0" /></channel><channel id="voltage2" type="output" ><attribute name="filter_fir_en" filename="out_voltage_filter_fir_en" value="0" /><attribute name="raw" filename="out_voltage2_raw" value="306" /><attribute name="rf_bandwidth" filename="out_voltage_rf_bandwidth" value="18000000" /><attribute name="rf_bandwidth_available" filename="out_voltage_rf_bandwidth_available" value="[200000 1 40000000]" /><attribute name="rf_port_select_available" filename="out_voltage_rf_port_select_available" value="A B" /><attribute name="sampling_frequency" filename="out_voltage_sampling_frequency" value="30720000" /><attribute name="sampling_frequency_available" filename="out_voltage_sampling_frequency_available" value="[2083333 1 61440000]" /><attribute name="scale" filename="out_voltage2_scale" value="1.000000" /></channel><channel id="temp0" type="input" ><attribute name="input" filename="in_temp0_input" value="41228" /></channel><channel id="voltage0" type="output" ><attribute name="filter_fir_en" filename="out_voltage_filter_fir_en" value="0" /><attribute name="hardwaregain" filename="out_voltage0_hardwaregain" value="-10.000000 dB" /><attribute name="hardwaregain_available" filename="out_voltage0_hardwaregain_available" value="[-89.750000 0.250000 0.000000]" /><attribute name="rf_bandwidth" filename="out_voltage_rf_bandwidth" value="18000000" /><attribute name="rf_bandwidth_available" filename="out_voltage_rf_bandwidth_available" value="[200000 1 40000000]" /><attribute name="rf_port_select" filename="out_voltage0_rf_port_select" value="A" /><attribute name="rf_port_select_available" filename="out_voltage_rf_port_select_available" value="A B" /><attribute name="rssi" filename="out_voltage0_rssi" value="0.00 dB" /><attribute name="sampling_frequency" filename="out_voltage_sampling_frequency" value="30720000" /><attribute name="sampling_frequency_available" filename="out_voltage_sampling_frequency_available" value="[2083333 1 61440000]" /></channel><channel id="voltage2" type="input" ><attribute name="bb_dc_offset_tracking_en" filename="in_voltage_bb_dc_offset_tracking_en" value="1" /><attribute name="filter_fir_en" filename="in_voltage_filter_fir_en" value="0" /><attribute name="gain_control_mode_available" filename="in_voltage_gain_control_mode_available" value="manual fast_attack slow_attack hybrid" /><attribute name="offset" filename="in_voltage2_offset" value="57" /><attribute name="quadrature_tracking_en" filename="in_voltage_quadrature_tracking_en" value="1" /><attribute name="raw" filename="in_voltage2_raw" value="531" /><attribute name="rf_bandwidth" filename="in_voltage_rf_bandwidth" value="18000000" /><attribute name="rf_bandwidth_available" filename="in_voltage_rf_bandwidth_available" value="[200000 1 56000000]" /><attribute name="rf_dc_offset_tracking_en" filename="in_voltage_rf_dc_offset_tracking_en" value="1" /><attribute name="rf_port_select_available" filename="in_voltage_rf_port_select_available" value="A_BALANCED B_BALANCED C_BALANCED A_N A_P B_N B_P C_N C_P TX_MONITOR1 TX_MONITOR2 TX_MONITOR1_2" /><attribute name="sampling_frequency" filename="in_voltage_sampling_frequency" value="30720000" /><attribute name="sampling_frequency_available" filename="in_voltage_sampling_frequency_available" value="[2083333 1 61440000]" /><attribute name="scale" filename="in_voltage2_scale" value="0.305250" /></channel><channel id="out" type="input" ><attribute name="voltage_filter_fir_en" filename="in_out_voltage_filter_fir_en" value="0" /></channel><attribute name="calib_mode" value="auto" /><attribute name="calib_mode_available" value="auto manual manual_tx_quad tx_quad rf_dc_offs rssi_gain_step" /><attribute name="dcxo_tune_coarse" value="ERROR:-19" /><attribute name="dcxo_tune_coarse_available" value="[0 0 0]" /><attribute name="dcxo_tune_fine" value="ERROR:-19" /><attribute name="dcxo_tune_fine_available" value="[0 0 0]" /><attribute name="ensm_mode" value="fdd" /><attribute name="ensm_mode_available" value="sleep wait alert fdd pinctrl pinctrl_fdd_indep" /><attribute name="filter_fir_config" value="FIR Rx: 0,0 Tx: 0,0" /><attribute name="gain_table_config" value="&lt;gaintable AD9361 type=FULL dest=3 start=1300000000 end=4000000000&gt;
-3, 0x00, 0x00, 0x20
-3, 0x00, 0x00, 0x00
-3, 0x00, 0x00, 0x00
-2, 0x00, 0x01, 0x00
-1, 0x00, 0x02, 0x00
0, 0x00, 0x03, 0x00
1, 0x00, 0x04, 0x00
2, 0x00, 0x05, 0x00
3, 0x01, 0x03, 0x20
4, 0x01, 0x04, 0x00
5, 0x01, 0x05, 0x00
6, 0x01, 0x06, 0x00
7, 0x01, 0x07, 0x00
8, 0x01, 0x08, 0x00
9, 0x01, 0x09, 0x00
10, 0x01, 0x0A, 0x00
11, 0x01, 0x0B, 0x00
12, 0x01, 0x0C, 0x00
13, 0x01, 0x0D, 0x00
14, 0x01, 0x0E, 0x00
15, 0x02, 0x09, 0x20
16, 0x02, 0x0A, 0x00
17, 0x02, 0x0B, 0x00
18, 0x02, 0x0C, 0x00
19, 0x02, 0x0D, 0x00
20, 0x02, 0x0E, 0x00
21, 0x02, 0x0F, 0x00
22, 0x02, 0x10, 0x00
23, 0x02, 0x2B, 0x20
24, 0x02, 0x2C, 0x00
25, 0x04, 0x27, 0x20
26, 0x04, 0x28, 0x00
27, 0x04, 0x29, 0x00
28, 0x04, 0x2A, 0x00
29, 0x04, 0x2B, 0x00
30, 0x24, 0x21, 0x20
31, 0x24, 0x22, 0x00
32, 0x44, 0x20, 0x20
33, 0x44, 0x21, 0x00
34, 0x44, 0x22, 0x00
35, 0x44, 0x23, 0x00
36, 0x44, 0x24, 0x00
37, 0x44, 0x25, 0x00
38, 0x44, 0x26, 0x00
39, 0x44, 0x27, 0x00
40, 0x44, 0x28, 0x00
41, 0x44, 0x29, 0x00
42, 0x44, 0x2A, 0x00
43, 0x44, 0x2B, 0x00
44, 0x44, 0x2C, 0x00
45, 0x44, 0x2D, 0x00
46, 0x44, 0x2E, 0x00
47, 0x44, 0x2F, 0x00
48, 0x44, 0x30, 0x00
49, 0x44, 0x31, 0x00
50, 0x64, 0x2E, 0x20
51, 0x64, 0x2F, 0x00
52, 0x64, 0x30, 0x00
53, 0x64, 0x31, 0x00
54, 0x64, 0x32, 0x00
55, 0x64, 0x33, 0x00
56, 0x64, 0x34, 0x00
57, 0x64, 0x35, 0x00
58, 0x64, 0x36, 0x00
59, 0x64, 0x37, 0x00
60, 0x64, 0x38, 0x00
61, 0x65, 0x38, 0x20
62, 0x66, 0x38, 0x20
63, 0x67, 0x38, 0x20
64, 0x68, 0x38, 0x20
65, 0x69, 0x38, 0x20
66, 0x6A, 0x38, 0x20
67, 0x6B, 0x38, 0x20
68, 0x6C, 0x38, 0x20
69, 0x6D, 0x38, 0x20
70, 0x6E, 0x38, 0x20
71, 0x6F, 0x38, 0x20
&lt;/gaintable&gt;" /><attribute name="multichip_sync" value="ERROR:-13" /><attribute name="rssi_gain_step_error" value="lna_error: 0 0 0 0
mixer_error: 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
gain_step_calib_reg_val: 0 0 0 0 0" /><attribute name="rx_path_rates" value="BBPLL:983040000 ADC:245760000 R2:122880000 R1:61440000 RF:30720000 RXSAMP:30720000" /><attribute name="trx_rate_governor" value="nominal" /><attribute name="trx_rate_governor_available" value="nominal highest_osr" /><attribute name="tx_path_rates" value="BBPLL:983040000 DAC:122880000 T2:122880000 T1:61440000 TF:30720000 TXSAMP:30720000" /><attribute name="waiting_for_supplier" value="0" /><attribute name="xo_correction" value="40000000" /><attribute name="xo_correction_available" value="[39992000 1 40008000]" /><debug-attribute name="adi,1rx-1tx-mode-use-rx-num" value="1" /><debug-attribute name="adi,1rx-1tx-mode-use-tx-num" value="1" /><debug-attribute name="adi,2rx-2tx-mode-enable" value="0" /><debug-attribute name="adi,agc-adc-large-overload-exceed-counter" value="10" /><debug-attribute name="adi,agc-adc-large-overload-inc-steps" value="2" /><debug-attribute name="adi,agc-adc-lmt-small-overload-prevent-gain-inc-enable" value="0" /><debug-attribute name="adi,agc-adc-small-overload-exceed-counter" value="10" /><debug-attribute name="adi,agc-attack-delay-extra-margin-us" value="1" /><debug-attribute name="adi,agc-dig-gain-step-size" value="4" /><debug-attribute name="adi,agc-dig-sat-ovrg-enable" value="0" /><debug-attribute name="adi,agc-dig-saturation-exceed-counter" value="3" /><debug-attribute name="adi,agc-gain-update-interval-us" value="1000" /><debug-attribute name="adi,agc-immed-gain-change-if-large-adc-overload-enable" value="0" /><debug-attribute name="adi,agc-immed-gain-change-if-large-lmt-overload-enable" value="0" /><debug-attribute name="adi,agc-inner-thresh-high" value="10" /><debug-attribute name="adi,agc-inner-thresh-high-dec-steps" value="1" /><debug-attribute name="adi,agc-inner-thresh-low" value="12" /><debug-attribute name="adi,agc-inner-thresh-low-inc-steps" value="1" /><debug-attribute name="adi,agc-lmt-overload-large-exceed-counter" value="10" /><debug-attribute name="adi,agc-lmt-overload-large-inc-steps" value="2" /><debug-attribute name="adi,agc-lmt-overload-small-exceed-counter" value="10" /><debug-attribute name="adi,agc-outer-thresh-high" value="5" /><debug-attribute name="adi,agc-outer-thresh-high-dec-steps" value="2" /><debug-attribute name="adi,agc-outer-thresh-low" value="18" /><debug-attribute name="adi,agc-outer-thresh-low-inc-steps" value="2" /><debug-attribute name="adi,agc-sync-for-gain-counter-enable" value="0" /><debug-attribute name="adi,aux-adc-decimation" value="256" /><debug-attribute name="adi,aux-adc-rate" value="40000000" /><debug-attribute name="adi,aux-dac-manual-mode-enable" value="1" /><debug-attribute name="adi,aux-dac1-active-in-alert-enable" value="0" /><debug-attribute name="adi,aux-dac1-active-in-rx-enable" value="0" /><debug-attribute name="adi,aux-dac1-active-in-tx-enable" value="0" /><debug-attribute name="adi,aux-dac1-default-value-mV" value="0" /><debug-attribute name="adi,aux-dac1-rx-delay-us" value="0" /><debug-attribute name="adi,aux-dac1-tx-delay-us" value="0" /><debug-attribute name="adi,aux-dac2-active-in-alert-enable" value="0" /><debug-attribute name="adi,aux-dac2-active-in-rx-enable" value="0" /><debug-attribute name="adi,aux-dac2-active-in-tx-enable" value="0" /><debug-attribute name="adi,aux-dac2-default-value-mV" value="0" /><debug-attribute name="adi,aux-dac2-rx-delay-us" value="0" /><debug-attribute name="adi,aux-dac2-tx-delay-us" value="0" /><debug-attribute name="adi,axi-half-dac-rate-enable" value="0" /><debug-attribute name="adi,bb-clk-change-dig-tune-enable" value="0" /><debug-attribute name="adi,clk-output-mode-select" value="0" /><debug-attribute name="adi,ctrl-outs-enable-mask" value="255" /><debug-attribute name="adi,ctrl-outs-index" value="0" /><debug-attribute name="adi,dc-offset-attenuation-high-range" value="6" /><debug-attribute name="adi,dc-offset-attenuation-low-range" value="5" /><debug-attribute name="adi,dc-offset-count-high-range" value="40" /><debug-attribute name="adi,dc-offset-count-low-range" value="50" /><debug-attribute name="adi,dc-offset-tracking-update-event-mask" value="5" /><debug-attribute name="adi,debug-mode-enable" value="0" /><debug-attribute name="adi,digital-interface-tune-fir-disable" value="1" /><debug-attribute name="adi,digital-interface-tune-skip-mode" value="0" /><debug-attribute name="adi,elna-bypass-loss-mdB" value="0" /><debug-attribute name="adi,elna-gain-mdB" value="0" /><debug-attribute name="adi,elna-gaintable-all-index-enable" value="0" /><debug-attribute name="adi,elna-rx1-gpo0-control-enable" value="0" /><debug-attribute name="adi,elna-rx2-gpo1-control-enable" value="0" /><debug-attribute name="adi,elna-settling-delay-ns" value="0" /><debug-attribute name="adi,ensm-enable-pin-pulse-mode-enable" value="0" /><debug-attribute name="adi,ensm-enable-txnrx-control-enable" value="0" /><debug-attribute name="adi,fagc-adc-large-overload-inc-steps" value="2" /><debug-attribute name="adi,fagc-allow-agc-gain-increase-enable" value="0" /><debug-attribute name="adi,fagc-dec-pow-measurement-duration" value="64" /><debug-attribute name="adi,fagc-energy-lost-stronger-sig-gain-lock-exit-cnt" value="8" /><debug-attribute name="adi,fagc-final-overrange-count" value="3" /><debug-attribute name="adi,fagc-gain-increase-after-gain-lock-enable" value="0" /><debug-attribute name="adi,fagc-gain-index-type-after-exit-rx-mode" value="0" /><debug-attribute name="adi,fagc-lmt-final-settling-steps" value="1" /><debug-attribute name="adi,fagc-lock-level-gain-increase-upper-limit" value="5" /><debug-attribute name="adi,fagc-lock-level-lmt-gain-increase-enable" value="1" /><debug-attribute name="adi,fagc-lp-thresh-increment-steps" value="1" /><debug-attribute name="adi,fagc-lp-thresh-increment-time" value="5" /><debug-attribute name="adi,fagc-lpf-final-settling-steps" value="1" /><debug-attribute name="adi,fagc-optimized-gain-offset" value="5" /><debug-attribute name="adi,fagc-power-measurement-duration-in-state5" value="64" /><debug-attribute name="adi,fagc-rst-gla-en-agc-pulled-high-enable" value="0" /><debug-attribute name="adi,fagc-rst-gla-engergy-lost-goto-optim-gain-enable" value="1" /><debug-attribute name="adi,fagc-rst-gla-engergy-lost-sig-thresh-below-ll" value="10" /><debug-attribute name="adi,fagc-rst-gla-engergy-lost-sig-thresh-exceeded-enable" value="1" /><debug-attribute name="adi,fagc-rst-gla-if-en-agc-pulled-high-mode" value="0" /><debug-attribute name="adi,fagc-rst-gla-large-adc-overload-enable" value="1" /><debug-attribute name="adi,fagc-rst-gla-large-lmt-overload-enable" value="1" /><debug-attribute name="adi,fagc-rst-gla-stronger-sig-thresh-above-ll" value="10" /><debug-attribute name="adi,fagc-rst-gla-stronger-sig-thresh-exceeded-enable" value="1" /><debug-attribute name="adi,fagc-state-wait-time-ns" value="260" /><debug-attribute name="adi,fagc-use-last-lock-level-for-set-gain-enable" value="1" /><debug-attribute name="adi,frequency-division-duplex-independent-mode-enable" value="0" /><debug-attribute name="adi,frequency-division-duplex-mode-enable" value="1" /><debug-attribute name="adi,gc-adc-large-overload-thresh" value="58" /><debug-attribute name="adi,gc-adc-ovr-sample-size" value="4" /><debug-attribute name="adi,gc-adc-small-overload-thresh" value="47" /><debug-attribute name="adi,gc-dec-pow-measurement-duration" value="8192" /><debug-attribute name="adi,gc-dig-gain-enable" value="0" /><debug-attribute name="adi,gc-lmt-overload-high-thresh" value="800" /><debug-attribute name="adi,gc-lmt-overload-low-thresh" value="704" /><debug-attribute name="adi,gc-low-power-thresh" value="24" /><debug-attribute name="adi,gc-max-dig-gain" value="15" /><debug-attribute name="adi,gc-rx1-mode" value="2" /><debug-attribute name="adi,gc-rx2-mode" value="2" /><debug-attribute name="adi,gc-use-rx-fir-out-for-dec-pwr-meas-enable" value="0" /><debug-attribute name="adi,gpo-manual-mode-enable" value="0" /><debug-attribute name="adi,gpo-manual-mode-enable-mask" value="0" /><debug-attribute name="adi,gpo0-inactive-state-high-enable" value="0" /><debug-attribute name="adi,gpo0-rx-delay-us" value="0" /><debug-attribute name="adi,gpo0-slave-rx-enable" value="0" /><debug-attribute name="adi,gpo0-slave-tx-enable" value="0" /><debug-attribute name="adi,gpo0-tx-delay-us" value="0" /><debug-attribute name="adi,gpo1-inactive-state-high-enable" value="0" /><debug-attribute name="adi,gpo1-rx-delay-us" value="0" /><debug-attribute name="adi,gpo1-slave-rx-enable" value="0" /><debug-attribute name="adi,gpo1-slave-tx-enable" value="0" /><debug-attribute name="adi,gpo1-tx-delay-us" value="0" /><debug-attribute name="adi,gpo2-inactive-state-high-enable" value="0" /><debug-attribute name="adi,gpo2-rx-delay-us" value="0" /><debug-attribute name="adi,gpo2-slave-rx-enable" value="0" /><debug-attribute name="adi,gpo2-slave-tx-enable" value="0" /><debug-attribute name="adi,gpo2-tx-delay-us" value="0" /><debug-attribute name="adi,gpo3-inactive-state-high-enable" value="0" /><debug-attribute name="adi,gpo3-rx-delay-us" value="0" /><debug-attribute name="adi,gpo3-slave-rx-enable" value="0" /><debug-attribute name="adi,gpo3-slave-tx-enable" value="0" /><debug-attribute name="adi,gpo3-tx-delay-us" value="0" /><debug-attribute name="adi,mgc-dec-gain-step" value="2" /><debug-attribute name="adi,mgc-inc-gain-step" value="2" /><debug-attribute name="adi,mgc-rx1-ctrl-inp-enable" value="0" /><debug-attribute name="adi,mgc-rx2-ctrl-inp-enable" value="0" /><debug-attribute name="adi,mgc-split-table-ctrl-inp-gain-mode" value="0" /><debug-attribute name="adi,qec-tracking-slow-mode-enable" value="0" /><debug-attribute name="adi,rf-rx-bandwidth-hz" value="18000000" /><debug-attribute name="adi,rf-tx-bandwidth-hz" value="18000000" /><debug-attribute name="adi,rssi-delay" value="1" /><debug-attribute name="adi,rssi-duration" value="1000" /><debug-attribute name="adi,rssi-restart-mode" value="3" /><debug-attribute name="adi,rssi-unit-is-rx-samples-enable" value="0" /><debug-attribute name="adi,rssi-wait" value="1" /><debug-attribute name="adi,rx-fastlock-delay-ns" value="0" /><debug-attribute name="adi,rx-fastlock-pincontrol-enable" value="0" /><debug-attribute name="adi,rx-rf-port-input-select" value="0" /><debug-attribute name="adi,rx-rf-port-input-select-lock-enable" value="1" /><debug-attribute name="adi,rx1-rx2-phase-inversion-enable" value="0" /><debug-attribute name="adi,split-gain-table-mode-enable" value="0" /><debug-attribute name="adi,tdd-skip-vco-cal-enable" value="0" /><debug-attribute name="adi,tdd-use-dual-synth-mode-enable" value="0" /><debug-attribute name="adi,temp-sense-decimation" value="256" /><debug-attribute name="adi,temp-sense-measurement-interval-ms" value="1000" /><debug-attribute name="adi,temp-sense-offset-signed" value="206" /><debug-attribute name="adi,temp-sense-periodic-measurement-enable" value="1" /><debug-attribute name="adi,trx-synthesizer-target-fref-overwrite-hz" value="80008000" /><debug-attribute name="adi,tx-attenuation-mdB" value="10000" /><debug-attribute name="adi,tx-fastlock-delay-ns" value="0" /><debug-attribute name="adi,tx-fastlock-pincontrol-enable" value="0" /><debug-attribute name="adi,tx-lo-powerdown-managed-enable" value="1" /><debug-attribute name="adi,tx-rf-port-input-select" value="0" /><debug-attribute name="adi,tx-rf-port-input-select-lock-enable" value="1" /><debug-attribute name="adi,txmon-1-front-end-gain" value="2" /><debug-attribute name="adi,txmon-1-lo-cm" value="48" /><debug-attribute name="adi,txmon-2-front-end-gain" value="2" /><debug-attribute name="adi,txmon-2-lo-cm" value="48" /><debug-attribute name="adi,txmon-dc-tracking-enable" value="0" /><debug-attribute name="adi,txmon-delay" value="511" /><debug-attribute name="adi,txmon-duration" value="8192" /><debug-attribute name="adi,txmon-high-gain" value="24" /><debug-attribute name="adi,txmon-low-gain" value="0" /><debug-attribute name="adi,txmon-low-high-thresh" value="37000" /><debug-attribute name="adi,txmon-one-shot-mode-enable" value="0" /><debug-attribute name="adi,update-tx-gain-in-alert-enable" value="0" /><debug-attribute name="bist_prbs" value="0" /><debug-attribute name="bist_timing_analysis" value="0" /><debug-attribute name="bist_tone" value="0" /><debug-attribute name="calibration_switch_control" value="0" /><debug-attribute name="digital_tune" value="0" /><debug-attribute name="direct_reg_access" value="0x0" /><debug-attribute name="gaininfo_rx1" value="71 76 0 0 0 0 0 0" /><debug-attribute name="gaininfo_rx2" value="ERROR:-11" /><debug-attribute name="gpo_set" value="0" /><debug-attribute name="initialize" value="0" /><debug-attribute name="loopback" value="0" /><debug-attribute name="multichip_sync" value="0" /></device><device id="iio:device2" name="xadc" ><channel id="voltage5" name="vccoddr" type="input" ><attribute name="label" filename="in_voltage5_vccoddr_label" value="vccoddr" /><attribute name="raw" filename="in_voltage5_vccoddr_raw" value="1832" /><attribute name="scale" filename="in_voltage5_vccoddr_scale" value="0.732421875" /></channel><channel id="voltage0" name="vccint" type="input" ><attribute name="label" filename="in_voltage0_vccint_label" value="vccint" /><attribute name="raw" filename="in_voltage0_vccint_raw" value="1369" /><attribute name="scale" filename="in_voltage0_vccint_scale" value="0.732421875" /></channel><channel id="voltage4" name="vccpaux" type="input" ><attribute name="label" filename="in_voltage4_vccpaux_label" value="vccpaux" /><attribute name="raw" filename="in_voltage4_vccpaux_raw" value="2449" /><attribute name="scale" filename="in_voltage4_vccpaux_scale" value="0.732421875" /></channel><channel id="temp0" type="input" ><attribute name="offset" filename="in_temp0_offset" value="-2219" /><attribute name="raw" filename="in_temp0_raw" value="2671" /><attribute name="scale" filename="in_temp0_scale" value="123.040771484" /></channel><channel id="voltage7" name="vrefn" type="input" ><attribute name="label" filename="in_voltage7_vrefn_label" value="vrefn" /><attribute name="raw" filename="in_voltage7_vrefn_raw" value="-14" /><attribute name="scale" filename="in_voltage7_vrefn_scale" value="0.732421875" /></channel><channel id="voltage1" name="vccaux" type="input" ><attribute name="label" filename="in_voltage1_vccaux_label" value="vccaux" /><attribute name="raw" filename="in_voltage1_vccaux_raw" value="2447" /><attribute name="scale" filename="in_voltage1_vccaux_scale" value="0.732421875" /></channel><channel id="voltage2" name="vccbram" type="input" ><attribute name="label" filename="in_voltage2_vccbram_label" value="vccbram" /><attribute name="raw" filename="in_voltage2_vccbram_raw" value="1367" /><attribute name="scale" filename="in_voltage2_vccbram_scale" value="0.732421875" /></channel><channel id="voltage3" name="vccpint" type="input" ><attribute name="label" filename="in_voltage3_vccpint_label" value="vccpint" /><attribute name="raw" filename="in_voltage3_vccpint_raw" value="1366" /><attribute name="scale" filename="in_voltage3_vccpint_scale" value="0.732421875" /></channel><channel id="voltage8" type="input" ><attribute name="raw" filename="in_voltage8_raw" value="3686" /><attribute name="scale" filename="in_voltage8_scale" value="0.244140625" /></channel><channel id="voltage6" name="vrefp" type="input" ><attribute name="label" filename="in_voltage6_vrefp_label" value="vrefp" /><attribute name="raw" filename="in_voltage6_vrefp_raw" value="1689" /><attribute name="scale" filename="in_voltage6_vrefp_scale" value="0.732421875" /></channel><attribute name="sampling_frequency" value="961538" /><attribute name="waiting_for_supplier" value="0" /></device><device id="iio:device3" name="cf-ad9361-dds-core-lpc" ><channel id="voltage0" type="output" ><scan-element index="0" format="le:S16/16&gt;&gt;0" /><attribute name="calibphase" filename="out_voltage0_calibphase" value="0.000000" /><attribute name="calibscale" filename="out_voltage0_calibscale" value="1.000000" /><attribute name="sampling_frequency" filename="out_voltage_sampling_frequency" value="30720000" /><attribute name="sampling_frequency_available" filename="out_voltage_sampling_frequency_available" value="30720000 3840000 " /></channel><channel id="voltage1" type="output" ><scan-element index="1" format="le:S16/16&gt;&gt;0" /><attribute name="calibphase" filename="out_voltage1_calibphase" value="0.000000" /><attribute name="calibscale" filename="out_voltage1_calibscale" value="1.000000" /><attribute name="sampling_frequency" filename="out_voltage_sampling_frequency" value="30720000" /><attribute name="sampling_frequency_available" filename="out_voltage_sampling_frequency_available" value="30720000 3840000 " /></channel><channel id="altvoltage3" name="TX1_Q_F2" type="output" ><attribute name="frequency" filename="out_altvoltage3_TX1_Q_F2_frequency" value="9279985" /><attribute name="label" filename="out_altvoltage3_TX1_Q_F2_label" value="TX1_Q_F2" /><attribute name="phase" filename="out_altvoltage3_TX1_Q_F2_phase" value="0" /><attribute name="raw" filename="out_altvoltage3_TX1_Q_F2_raw" value="1" /><attribute name="sampling_frequency" filename="out_altvoltage_sampling_frequency" value="30720000" 